### ISSUE TITLE
在自己的环境里训练不起来

### ISSUE THREAD

**Issue by xiaoheizi123** [Green-Wood/CoMER#5]
在docker中执行，按照代码要求安装了环境

执行训练语句，提示需要添加subcommand语句，添加fit后报错：
`python train.py --config config.yaml fit
/opt/conda/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
usage: train.py [-h] [--config CONFIG] [--print_config[=flags]]
                {fit,validate,test,predict,tune} ...
train.py: error: Configuration check failed :: Key "fit.model.self_coverage" is required but not included in config object or its value is None.`

**Comment by xiaoheizi123** [comment]
按照conda环境配置了一遍，可以使用语句‘python train.py --config config.yaml’ 训练起来，之前应该是环境问题

**Comment by SuperHHzy** [comment]
你好，我在运行train.py的时候，出现了这个报错，你在运行代码的时候遇到过吗？
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from pytorch_lightning.plugins.training_type.ddp import DDPPlugin
  File "F:\Anaconda\envs\pytorch\lib\site-packages\pytorch_lightning\__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "F:\Anaconda\envs\pytorch\lib\site-packages\pytorch_lightning\metrics\__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "F:\Anaconda\envs\pytorch\lib\site-packages\pytorch_lightning\metrics\classification\__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "F:\Anaconda\envs\pytorch\lib\site-packages\pytorch_lightning\metrics\classification\accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "F:\Anaconda\envs\pytorch\lib\site-packages\pytorch_lightning\metrics\utils.py", line 29, in <module>
    from pytorch_lightning.utilities import rank_zero_deprecation
  File "F:\Anaconda\envs\pytorch\lib\site-packages\pytorch_lightning\utilities\__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "F:\Anaconda\envs\pytorch\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 30, in <module>
    if _compare_version("torchtext", operator.ge, "0.9.0"):
  File "F:\Anaconda\envs\pytorch\lib\site-packages\pytorch_lightning\utilities\imports.py", line 54, in _compare_version
    pkg = importlib.import_module(package)
  File "F:\Anaconda\envs\pytorch\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "F:\Anaconda\envs\pytorch\lib\site-packages\torchtext\__init__.py", line 9, in <module>
    from . import vocab
  File "F:\Anaconda\envs\pytorch\lib\site-packages\torchtext\vocab\__init__.py", line 11, in <module>
    from .vocab_factory import (
  File "F:\Anaconda\envs\pytorch\lib\site-packages\torchtext\vocab\vocab_factory.py", line 4, in <module>
    from torchtext._torchtext import (
ImportError: DLL load failed while importing _torchtext: 找不到指定的程序。

**Comment by xiaoheizi123** [comment]
torchtext  没装或者版本不对吧

**Comment by SuperHHzy** [comment]
> torchtext 没装或者版本不对吧

感谢你的答复，我建立了一个新的环境，在新的环境中下载需要的依赖，这个问题就解决了。但是出现了这个错误，我有点不知措施。
![image](https://user-images.githubusercontent.com/107484371/219562421-8afbf0e5-ee5d-4c50-9add-e3af2f619556.png)

**Comment by SuperHHzy** [comment]
感谢，这个问题我已经解决了。

**Comment by gaoshaojie0708** [comment]
您好想问下您用的设备是什么，我用两块4090还会爆显存？我不是很理解哪里出了问题。conda install pytorch=1.8.1 torchvision=0.2.2 cudatoolkit=11.1 pillow=8.4.0 -c pytorch -c nvidia
# training dependency
conda install pytorch-lightning=1.4.9 torchmetrics=0.6.0 -c conda-forge是根据作者环境配置的。

**Comment by coloteong20** [comment]
> 感谢，这个问题我已经解决了。

您好，请问你记得你是怎么解决的吗？我也遇到了一模一样的问题
